version: '3'
networks:
  default:
    external:
      name: docker_default

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "${USER_UID}"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:z
      - ./prometheus_db:/var/lib/prometheus:z
      - ./prometheus_db:/prometheus:z
      - ./prometheus_db:/etc/prometheus:z
      - ./alert.rules:/etc/prometheus/alert.rules:z
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.route-prefix=/'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    restart: unless-stopped
    ports:
      - '9090:9090'

  node-exporter:
    image: prom/node-exporter
    ports:
      - '9100:9100'

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - '8082:8080'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  grafana:
    image: grafana/grafana
    user: "${USER_UID}"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD
      - GF_SMTP_ENABLED
      - GF_SMTP_HOST
      - GF_SMTP_USER
      - GF_SMTP_PASSWORD
      - GF_SMTP_FROM_ADDRESS
      - GF_SMTP_FROM_NAME
      - GF_SMTP_STARTTLS_POLICY
      - GF_SERVER_ROOT_URL
      - GF_SERVE_FROM_SUB_PATH
    volumes:
      - ./grafana_db:/var/lib/grafana:z
    depends_on:
      - prometheus
    ports:
      - '3100:3000'

  grok:
    image: cvvnx1/grok_exporter
    container_name: grok_exporter
    ports:
      - 9144:9144
    volumes:
      - /var/log/httpd:/log
      - ./grok_exporter_config_path.yml:/grok/config.yml
    #restart: unless-stopped

  geoip:
    image: greegorey/geoip-exporter
    container_name: geoip_exporter
    volumes:
      - /etc/ssl/certs:/etc/ssl/certs:ro
    ports:
      - 9300:9300

#  reports:
#    image: skedler/reports:latest
#    container_name: reports
#    privileged: true
#    cap_add:
#      - SYS_ADMIN
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#      - reportdata:/var/lib/skedler
#      - ./reporting.yml:/opt/skedler/config/reporting.yml
#    ports:
#      - 3001:3001
