global:
  scrape_interval: 60s
  external_labels:
    monitor: 'devopsage-monitor'
scrape_configs:
  - job_name: 'prometheus' 
    static_configs: 
      - targets: ['prometheus:9090']
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['monitoring_node-exporter_1:9100']
  - job_name: 'cAdvisor' 
    static_configs:
      - targets: ['monitoring_cadvisor_1:8080']
  - job_name: 'grok' 
    static_configs:
      - targets: ['grok_exporter:9144']
  - job_name: 'grafana' 
    static_configs:
      - targets: ['monitoring_grafana_1:3000']
  - job_name: 'GeoIPExporter'
    scrape_interval: 60s
    static_configs:
      - targets: ['geoip_exporter:9300']
