global:
  scrape_interval: 60s
  external_labels:
    monitor: 'cioos-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['server_monitoring_node-exporter_1:9100']
  - job_name: 'cAdvisor'
    scrape_interval: 30s
    static_configs:
      - targets: ['server_monitoring_cadvisor_1:8080']
  - job_name: 'grok'
    static_configs:
      - targets: ['grok_exporter:9144']
  - job_name: 'grafana'
    static_configs:
      - targets: ['server_monitoring_grafana_1:3000']
  - job_name: 'GeoIPExporter'
    scrape_interval: 60s
    static_configs:
      - targets: ['geoip_exporter:9300']
